### ISSUE TITLE
Cant download the datasets

### ISSUE THREAD

**Issue by 9Cirno9** [neheller/kits23#21]
![image](https://github.com/user-attachments/assets/bac95ef6-d07a-4c76-ab5a-249a7f71e03c)
The progress has always been 0%，my env is：
![image](https://github.com/user-attachments/assets/e1671c44-fa3f-4a50-a7c8-f0539cf5ecd6)
Do you have any suggestions？Thanks a lot！

**Comment by manuel-lincbiotech** [comment]
Same problem here, Just followed the instruction as in the readme also tried with a different python version 3.9. But since @9Cirno9 seems to have the same problem I don´t think it's related to python version. After a while in 0% in just ends up with the error:

> Found 489 cases to download
> Dowloading case_00000...:   0%|                                                                                                                                       | 0/489 [00:00<?, ?it/s] 
> Failed to download case_00000. Retrying...
> Dowloading case_00000...:   0%|                                                                                                                                       | 0/489 [10:36<?, ?it/s]
> Traceback (most recent call last):
>   File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 38, in download_case
>     urllib.request.urlretrieve(url, str(tmp_pth))
>   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 278, in urlretrieve
>     raise ContentTooShortError(
> urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 225683164 out of 225959569 bytes>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\User\Desktop\minerva projects\kidney_dataset\venv\Scripts\kits23_download_data-script.py", line 33, in <module>
>     sys.exit(load_entry_point('kits23', 'console_scripts', 'kits23_download_data')())
>   File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\entrypoints.py", line 9, in download_data_entrypoint
>     download_dataset()
>   File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 77, in download_dataset
>     download_case(case_num, pbar)
>   File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 52, in download_case
>     download_case(case_num, pbar, retry=False)
>   File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 56, in download_case
>     cleanup(tmp_pth, e)
>   File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 29, in cleanup
>     raise(e)
>   File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 38, in download_case
>     urllib.request.urlretrieve(url, str(tmp_pth))
>   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 278, in urlretrieve
>     raise ContentTooShortError(
> urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 225720172 out of 225959569 bytes>

Any suggestions or alternatives appreciated
Thanks in advance.

**Comment by buni-alex** [comment]
Same problem. When they work, the downloads are very very slow, but most of them fail anyway after a long period of waiting. It also always seems like only a few bytes off the total fail to download.

**Comment by dt-yuhui** [comment]
@neheller Same question. Any suggestion?

**Comment by loijilai** [comment]
Same here

**Comment by YongchengYAO** [comment]
same

**Comment by 4lparslan** [comment]
> Same problem here, Just followed the instruction as in the readme also tried with a different python version 3.9. But since [@9Cirno9](https://github.com/9Cirno9) seems to have the same problem I don´t think it's related to python version. After a while in 0% in just ends up with the error:
> 
> > Found 489 cases to download
> > Dowloading case_00000...:   0%|                                                                                                                                       | 0/489 [00:00<?, ?it/s]
> > Failed to download case_00000. Retrying...
> > Dowloading case_00000...:   0%|                                                                                                                                       | 0/489 [10:36<?, ?it/s]
> > Traceback (most recent call last):
> > File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 38, in download_case
> > urllib.request.urlretrieve(url, str(tmp_pth))
> > File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 278, in urlretrieve
> > raise ContentTooShortError(
> > urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 225683164 out of 225959569 bytes>
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "C:\Users\User\Desktop\minerva projects\kidney_dataset\venv\Scripts\kits23_download_data-script.py", line 33, in 
> > sys.exit(load_entry_point('kits23', 'console_scripts', 'kits23_download_data')())
> > File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\entrypoints.py", line 9, in download_data_entrypoint
> > download_dataset()
> > File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 77, in download_dataset
> > download_case(case_num, pbar)
> > File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 52, in download_case
> > download_case(case_num, pbar, retry=False)
> > File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 56, in download_case
> > cleanup(tmp_pth, e)
> > File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 29, in cleanup
> > raise(e)
> > File "c:\users\user\desktop\minerva projects\kidney_dataset\kits23\kits23\download.py", line 38, in download_case
> > urllib.request.urlretrieve(url, str(tmp_pth))
> > File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 278, in urlretrieve
> > raise ContentTooShortError(
> > urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 225720172 out of 225959569 bytes>
> 
> Any suggestions or alternatives appreciated Thanks in advance.

I was facing the same issue and i had to restart the download process multiple times. If you have some time, the solution is simple. Create a .bat file and automate the retry process:

```
@echo off
echo Venv activating
call "D:\Projects\Kits23\.venv\Scripts\activate.bat"

:loop
echo [%time%] Downloading starting...
call kits23_download_data

if %ERRORLEVEL% neq 0 (
    echo.
    echo [%time%] !!! ERROR !!! 
    echo Waiting for 5 seconds and retrying...
    echo.
    timeout /t 5
    goto loop
)

echo.
echo [%time%] Downloading completed successfully.
pause
```

**Comment by CheeMinHao** [comment]
I've managed to discover that amending the `download.py` 's `download_case` function to download the imaging in chunks rather than the whole thing would work:

```python
import requests
import shutil
from time import sleep

def download_case(case_num: int, pbar, retry=True):
    remote_name = f"master_{case_num:05d}.nii.gz"
    url = f"https://kits19.sfo2.digitaloceanspaces.com/{remote_name}"
    destination = get_destination(f"case_{case_num:05d}", True)
    tmp_pth = destination.parent / f".partial.{destination.name}"

    try:
        with requests.get(url, stream=True, timeout=(10, 60)) as r:
            r.raise_for_status()
            with open(tmp_pth, "wb") as f:
                for chunk in r.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        f.write(chunk)
        shutil.move(tmp_pth, destination)

    except KeyboardInterrupt:
        pbar.close()
        cleanup(tmp_pth, None)
        raise

    except Exception as e:
        cleanup(tmp_pth, e)
        if retry:
            print(f"\nFailed to download case_{case_num:05d}. Retrying...")
            sleep(5)
            return download_case(case_num, pbar, retry=False)
        raise
```

I'm guessing it's because the downloading is performed once every file and, given it's a big file, the downloading time probably went over the timeout threshold. This code amendment works for me and I was able to download all cases without the above error showing.

Hope it helps.

**Comment by Sara666-LI** [comment]
> I've managed to discover that amending the `download.py` 's `download_case` function to download the imaging in chunks rather than the whole thing would work:
> 
> import requests
> import shutil
> from time import sleep
> 
> def download_case(case_num: int, pbar, retry=True):
>     remote_name = f"master_{case_num:05d}.nii.gz"
>     url = f"https://kits19.sfo2.digitaloceanspaces.com/{remote_name}"
>     destination = get_destination(f"case_{case_num:05d}", True)
>     tmp_pth = destination.parent / f".partial.{destination.name}"
> 
>     try:
>         with requests.get(url, stream=True, timeout=(10, 60)) as r:
>             r.raise_for_status()
>             with open(tmp_pth, "wb") as f:
>                 for chunk in r.iter_content(chunk_size=1024 * 1024):
>                     if chunk:
>                         f.write(chunk)
>         shutil.move(tmp_pth, destination)
> 
>     except KeyboardInterrupt:
>         pbar.close()
>         cleanup(tmp_pth, None)
>         raise
> 
>     except Exception as e:
>         cleanup(tmp_pth, e)
>         if retry:
>             print(f"\nFailed to download case_{case_num:05d}. Retrying...")
>             sleep(5)
>             return download_case(case_num, pbar, retry=False)
>         raise
> I'm guessing it's because the downloading is performed once every file and, given it's a big file, the downloading time probably went over the timeout threshold. This code amendment works for me and I was able to download all cases without the above error showing.
> 
> Hope it helps.

Thanks a lot, I solved this issue based on your cases, it workd when I changed timeout=(10, 60) to timeout=(10, 80), coz timeout=(10, 60) still went over the timeout threshold.
