### ISSUE TITLE
Error during download

### ISSUE THREAD

**Issue by mzenk** [neheller/kits23#3]
Hi, 
thank you for the promising challenge! I'm trying to download the KiTS23 dataset via kits23_download_data, but after a while, I got this error:
```
Dowloading case_00031...:   6%|████████████▎                                                                                                                                                                                      | 31/489 [20:21<5:00:45, 39.40s/it]
Traceback (most recent call last):                               
  File "/mnt/datasets/data/kits23/.conda_env/bin/kits23_download_data", line 33, in <module>                                      
    sys.exit(load_entry_point('kits23', 'console_scripts', 'kits23_download_data')())                                             
  File "/mnt/datasets/data/kits23/kits23/entrypoints.py", line 9, in download_data_entrypoint                                     
    download_dataset()                                           
  File "/mnt/datasets/data/kits23/kits23/download.py", line 77, in download_dataset                                               
    download_case(case_num, pbar)                                
  File "/mnt/datasets/data/kits23/kits23/download.py", line 56, in download_case                                                  
    cleanup(tmp_pth, e)                                          
  File "/mnt/datasets/data/kits23/kits23/download.py", line 29, in cleanup                                                        
    raise(e)                                                     
  File "/mnt/datasets/data/kits23/kits23/download.py", line 38, in download_case                                                  
    urllib.request.urlretrieve(url, str(tmp_pth))                
  File "/mnt/datasets/data/kits23/.conda_env/lib/python3.10/urllib/request.py", line 280, in urlretrieve                          
    raise ContentTooShortError(                                  
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 50140229 out of 50504430 bytes> 
```
Is it normal that this happens and should I just retry download with the same command? How is the case that didn't download successfully handled?

Cheers,
Max

**Comment by neheller** [comment]
Hi Max,

I've encountered this error once or twice myself during testing. To be honest, I'm not exactly sure what causes it other than maybe an interrupted network connection. You are definitely safe to simply re-run the same command. The script should recognize that case 31 didn't download completely and handle it accordingly.

**Comment by mzenk** [comment]
Ok, thanks, I'll try that.

**Comment by neheller** [comment]
Great. Feel free to reopen if you continue to have this problem.

**Comment by haozixin** [comment]
But, for this example, if I run the same command, it will start to download case_00032. Does it mean case 31 has downloaded completely? or it's an uncomplete file just leave there.
